Repository Kinto/kinto, pull requests merged in 2024-01, with the labels that each got.

#3351 Bump Kinto Admin to 3.0.1
  kinto/plugins/admin/VERSION
  scripts/build-kinto-admin.sh
Labels: dependencies

#3362 Merge Github workflows files into `test.yml`
  .github/workflows/admin.yml
  .github/workflows/docs.yml
  .github/workflows/functional.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  Makefile
Labels: productivity

#3360 Decouple `kinto-redis` from this repository
  docs/commandline.rst
  docs/configuration/settings.rst
  docs/tutorials/install.rst
  kinto/__main__.py
  kinto/config/__init__.py
  setup.cfg
  tests/test_config.py
  tests/test_main.py
Labels: breaking-change

#3357 Get rid of tox
  .github/workflows/test.yml
  .gitignore
  MANIFEST.in
  Makefile
  dev-requirements.txt
  docs/community.rst
  setup.cfg
  tox.ini
Labels: productivity

#3366 Move community files to `.github/` folder
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
Labels: documentation

#3364 ShellCheck `scripts/` folder
  .github/workflows/test.yml
  scripts/build-kinto-admin.sh
Labels: score: productivity

#3361 Force labels on pull-requests, and add sections in generated changelog
  .github/release.yml
  .github/workflows/labels.yaml
Labels: score: productivity

#3359 Switch from `setup.cfg`/`setup.py` to `pyproject.toml`
  .github/workflows/test.yml
  Dockerfile
  MANIFEST.in
  Makefile
  dev-requirements.txt
  docs/community.rst
  docs/configuration/production.rst
  pyproject.toml
  requirements.in
  requirements.txt
  setup.cfg
  setup.py
Labels: score: productivity

#3367 Run functional tests on freshly built container
  .github/workflows/test.yml
Labels: enhancement

#3369 Do not install dev dependencies in Docker image
  Dockerfile
  Makefile
  constraints.in
  constraints.txt
Labels: dependencies

#3372 Fix Docker image build frozen step
  Dockerfile
  pyproject.toml
Labels: bug

#3376 Read admin assets version from configured folder
  docs/kinto-admin.rst
  kinto/plugins/admin/__init__.py
  tests/plugins/test_admin.py
Labels: bug, breaking-change
