Repository Kinto/kinto, pull requests merged in 2025-05, with the labels that each got.

#3539 Use explicit seconds suffix for duration metrics
  kinto/core/metrics.py
  kinto/plugins/prometheus.py
  tests/core/resource/test_events.py
  tests/core/test_metrics.py
  tests/plugins/test_history.py
Labels: bug, breaking-change

#3541 Remove `status` from request_size and request_duration_seconds labels
  kinto/core/initialization.py
  tests/core/test_initialization.py
  tests/test_views_metrics.py
Labels: enhancement, breaking-change

#3545 Improve Makefile to avoid reinstall on each run
  Makefile
  docs/community.rst
Labels: bug

#3546 Fixing duplicated prometheus metrics. Resolves remote-settings #872
  kinto/plugins/prometheus.py
Labels: bug

#3542 Ref mozilla/remote-settings#884: Fix duplicated metrics issue
  .github/workflows/test.yml
  Makefile
  kinto/plugins/prometheus.py
  pyproject.toml
  tests/functional.ini
  tests/functional.py
  tests/plugins/test_prometheus.py
Labels: enhancement

#3544 Fixes #3533: Add ability to disable certain default metrics and adjust buckets
  docs/configuration/settings.rst
  kinto/plugins/prometheus.py
  tests/plugins/test_prometheus.py
Labels: enhancement

#3548 Fix request duration duration unit
  kinto/core/initialization.py
Labels: bug
