Repository Kinto/kinto, pull requests merged in 2025-02, with the labels that each got.

#3489 Fix crash when error has type bytes (fixes #3488)
  kinto/core/errors.py
  tests/test_views_buckets.py
Labels: bug

#3358 Add workflow to check for Kinto Admin updates
  .github/workflows/scheduled.yml
Labels: blocked

#3491 Lint and fix Github Actions
  .github/workflows/publish.yml
  .github/workflows/scheduled.yml
  .github/workflows/test.yml
Labels: bug

#3493 Fix exception in in-memory permission backend (fixes #2687)
  kinto/core/permission/memory.py
  kinto/core/permission/testing.py
Labels: bug

#3496 Switch to `psycopg-binary` library
  Dockerfile
  constraints.in
  constraints.txt
  pyproject.toml
Labels: dependencies

#3499 Re-enable readthedocs
  .readthedocs.yaml
  Makefile
Labels: documentation

#3497 Vendor `cornice` and `cornice.ext.swagger`
  constraints.in
  constraints.txt
  docs/conf.py
  docs/requirements.txt
  docs/troubleshooting.rst
  kinto/core/__init__.py
  kinto/core/cornice/__init__.py
  kinto/core/cornice/cors.py
  kinto/core/cornice/errors.py
  kinto/core/cornice/pyramidhook.py
  kinto/core/cornice/renderer.py
  kinto/core/cornice/resource.py
  kinto/core/cornice/service.py
  kinto/core/cornice/util.py
  kinto/core/cornice/validators/__init__.py
  kinto/core/cornice/validators/_colander.py
  kinto/core/cornice/validators/_marshmallow.py
  kinto/core/cornice_swagger/__init__.py
  kinto/core/cornice_swagger/converters/__init__.py
  kinto/core/cornice_swagger/converters/exceptions.py
  kinto/core/cornice_swagger/converters/parameters.py
  kinto/core/cornice_swagger/converters/schema.py
  kinto/core/cornice_swagger/swagger.py
  kinto/core/cornice_swagger/templates/index.html
  kinto/core/cornice_swagger/templates/index_script_template.html
  kinto/core/cornice_swagger/util.py
  kinto/core/cornice_swagger/views.py
  kinto/core/openapi.py
  kinto/core/resource/viewset.py
  kinto/core/testing.py
  kinto/core/utils.py
  kinto/core/views/batch.py
  kinto/core/views/openapi.py
  kinto/plugins/flush.py
  kinto/plugins/openid/views.py
  kinto/views/contribute.py
  pyproject.toml
  tests/core/resource/test_viewset.py
  tests/core/test_openapi.py
Labels: dependencies

#3502 Remove obsolete sections from docs (fixes #307, fixes #330, fixes #508)
  docs/api/1.x/openid.rst
  docs/community.rst
  docs/concepts.rst
  docs/configuration/good-practices.rst
  docs/configuration/settings.rst
  docs/core/glossary.rst
  docs/faq.rst
  docs/images/architecture.svg
  docs/images/logo-demos.svg
  docs/images/logo-indexing.svg
  docs/images/logo-livesync.svg
  docs/images/logo-offline.svg
  docs/images/logo-signature.svg
  docs/overview.rst
  docs/troubleshooting.rst
  docs/tutorials/app-examples.rst
  docs/tutorials/authentication-github.rst
  docs/tutorials/client-side-encryption.rst
  docs/tutorials/first-steps.rst
  docs/tutorials/index.rst
  docs/tutorials/install.rst
  docs/tutorials/notifications-custom.rst
  docs/tutorials/notifications-websockets.rst
  docs/tutorials/permissions.rst
  docs/tutorials/write-plugin.rst
  tests/test_views_permissions.py
Labels: documentation

#3503 Remove 'kinto.plugins.quotas' (fixes #2894)
  docs/api/1.x/index.rst
  docs/api/1.x/quotas.rst
  docs/commandline.rst
  docs/configuration/settings.rst
  docs/images/logo-quotas.svg
  docs/overview.rst
  kinto/__main__.py
  kinto/config/kinto.tpl
  kinto/core/storage/postgresql/pool.py
  kinto/plugins/quotas/__init__.py
  kinto/plugins/quotas/listener.py
  kinto/plugins/quotas/scripts.py
  kinto/plugins/quotas/utils.py
  kinto/scripts.py
  tests/plugins/test_quotas.py
  tests/test_configuration/test.ini
  tests/test_main.py
  tests/test_scripts.py
Labels: breaking-change

#3505 Remove accounts emailing features
  .gitignore
  constraints.in
  constraints.txt
  docs/api/1.x/accounts.rst
  docs/api/index.rst
  docs/configuration/settings.rst
  kinto/config/kinto.tpl
  kinto/core/views/errors.py
  kinto/plugins/accounts/__init__.py
  kinto/plugins/accounts/authentication.py
  kinto/plugins/accounts/mails.py
  kinto/plugins/accounts/utils.py
  kinto/plugins/accounts/views.py
  kinto/plugins/accounts/views/validation.py
  pyproject.toml
  tests/core/test_views_errors.py
  tests/plugins/test_accounts.py
  tests/test_configuration/test.ini
Labels: breaking-change

#3508 Remove mentions of kinto-storage.org demo
  README.rst
  SUPPORT.md
  docs/api/1.x/authentication.rst
  docs/api/1.x/openapi.rst
  docs/api/1.x/permissions.rst
  kinto/contribute.json
  kinto/views/contribute.py
  pyproject.toml
  tests/test_views_contribute.py
Labels: documentation
